---
title: "Modeling through the pandemic"
description: A series of posts about how modeling helped me stayed sane in 2020
author:
  - name: Enrico Manlapig
date: 02-01-2021
categories: 
  - modeling
output:
  distill::distill_article:
    self_contained: false
---

The next few posts will be about the early part of 2020, when COVID-19 really started twisting and turning life in the US.  In my little corner of the world, this was March and April.  There was no talk yet of masks, lockdowns, or waves.  We were still experimenting with elbow bumps and watching the crises unfolding in Wuhan and Italy. In early March, I took a cautious trip to deliver a workshop about how to make high quality decisions.  After I returned home, California became the first state to lock down, which was when things really got serious. Goodness knows you couldn't buy toilet paper.  

The uncertainty and change and flood of information left me in a headspin.  It didn't help that I was doom-scrolling, a new term I learned for focusing on bad news (all news was bad news). I was teaching "asynchronously" (another term I learned during this period that means delivering pre-recorded lectures) and working like crazy to keep up. We were all learning how to use Zoom and getting used to being at home with our families.  When Easter rolled around, I was thankful for a week-long break.  Like many others, I took the opportunity to re-watch *Contagion* and *Outbreak* before gathering my thoughts.  


As an DA-geek, I experienced a bizarre cognitive dissonance.  Part of me was very thankful that I didn't have to make the difficult decisions that government and organizational leaders did.  These are big decisions fraught with complexity and uncertainty.  Another part of me, though, felt as though no one is better equipped to deal with complexity and uncertainty than DA-geeks.  The DA community has always felt a little ignored and it seemed obvious it really had something important to contribute at this time.  My data side envied those that were doing the analysis while I was  teaching finance.  At this moment I wanted to be doing R rather than teaching R.

So over Easter break I asked myself, if I were supporting some of these decisions, what analysis would I do?  I started modeling and I felt free to  explore whatever was bothering me.  Modeling helps me clarify my thoughts, which is what I needed at this time.  Even though there wasn't a client, I suppose I was modeling for myself.  

Over the next few weeks, I want to share some of these thoughts with you.  To be perfectly clear, I am not an epidemiologist and I make no claim that my work is any way appropriate for informing science or  policy.  What follows are my own thoughts and I wrote them for my own sanity and catharsis.

Do you find modeling cathartic? Did you do anything like this during quarantine?
